---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example-deployment
  labels:
    app: node-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
      annotations:
        laas.uninett.no/enabled: 'true'
        laas.uninett.no/service: filebeatk8s
        laas.uninett.no/type: json
        laas.uninett.no/token: abc
    spec:
      containers:
      - name: node-example
        image: havlan/node-express-example
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /var/log
            name: varlog
      - name: specificfilelog
        image: busybox
        args: [/bin/sh, -c, 'tail -n+1 -f /var/log/express-k8s-example/express-example-app.log']
        volumeMounts:
          - mountPath: /var/log
            name: varlog
      volumes:
        - name: varlog
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: node-example
  labels:
    app: node-example
  annotations:
    laas.uninett.no/enabled: 'true'
    laas.uninett.no/service: filebeatk8s
    laas.uninett.no/type: json
    laas.uninett.no/token: abc
spec:
  selector:
    app: node-example
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
