---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
        laas-service: filebeatk8s
        laas-type: json
        laas-token: abc
      annotations:
        uninett/logging: 'true'
        co.elastic.logs/multiline.pattern: '^\['
        co.elastic.logs/multiline.negate: 'true'
        co.elastic.logs/multiline.match: after
    spec:
      containers:
      - name: node-example
        image: havlan/node-express-example
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-example
  labels:
    app: node-example
    laas-service: filebeatk8s
    laas-type: json
    laas-token: abc
  annotations:
    uninett/logging: 'true'
    co.elastic.logs/multiline.pattern: '^\['
    co.elastic.logs/multiline.negate: 'true'
    co.elastic.logs/multiline.match: after
spec:
  selector:
    app: node-example
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
