---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
        ut-service: filebeatk8s
        ut-type: syslog
        ut-token: express_token_fb
      annotations:
        uninett/logging: 'true'
    spec:
      containers:
      - name: node-example
        image: havlan/node-express-example
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-example
  labels:
    app: node-example
    ut-service: filebeatk8s
    ut-type: syslog
    ut-token: express_token_fb
  annotations:
    uninett/logging: 'true'
spec:
  selector:
    app: node-example
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
